name: Comma master-ci puller
on:
  schedule:
    - cron: '10 23 * * *'
  workflow_dispatch:





jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master-ci             # set the branch to merge to

      # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
        with:
          upstream_repository: commaai/openpilot
          upstream_branch: master-ci
          target_branch: master-ci
          git_pull_args: '-s recursive -Xtheirs --allow-unrelated-histories'                # optional arg use, defaults to simple 'pull'
          github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication



      # Step 3: Display a message if 'sync' step had new commits (simple test)
      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits
        run: echo "There were new commits."

      # Step 4: Print a helpful timestamp for your records (not required, just nice)
      - name: Timestamp
        run: date
