# This is a basic workflow to help you get started with Actions

name: automatic merge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 075-kegman-lqr branch
on:
  pull_request:
    branches: [ 075-kegman-lqr, 075-kegman-lqr-develop, 081-kegman, 081-kegman-develop ]
    types: [edited, opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  python_linter:
    name: python lint - GM cars
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



      - name: Python Linter
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: selfdrive/car/gm/** selfdrive/car/*.py
          use-pylint: true
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: --disable=C,R,E0401,W0612,W0101,W0611,W0613,W0511,W0311,W0954,W0703,W0621,W0201
          extra-flake8-options: --select=F21,F822,F823,F831,F811,F812,E999

  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: python_linter
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        if: ${{ github.base_ref }} == "075-kegman-lqr" || ${{ github.base_ref }} == "081-kegman"
        with:
          # 이벤트를 트리거하고 싶은 라벨 이름을 설정합니다. 기본 이름은 "automerge" 입니다.
          label-name: automerge
          # 최소 리뷰어 수를 지정할 수 있습니다. 기본은 1명입니다.
          reviewers-number: 0
          # "merge", "squash", "rebase" 중 한가지를 선택할 수 있습니다. 기본값은 "merge" 입니다
          merge-method: merge
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        if:  ${{ github.base_ref }} == "075-kegman-lqr-develop" || ${{ github.base_ref }} == "081-kegman-develop"
        with:
          # 이벤트를 트리거하고 싶은 라벨 이름을 설정합니다. 기본 이름은 "automerge" 입니다.
          label-name: automerge
          # 최소 리뷰어 수를 지정할 수 있습니다. 기본은 1명입니다.
          reviewers-number: 0
          # "merge", "squash", "rebase" 중 한가지를 선택할 수 있습니다. 기본값은 "merge" 입니다
          merge-method: squash
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.GITHUB_TOKEN }}